### ISSUE TITLE
Significant Number of Points at Coordinates (0,0,0) in ouster_points .bin Files

### ISSUE THREAD

**Issue by samuelss1996** [l1997i/DurLAR#10]
I have been exploring the DurLAR dataset, specifically the ouster_points .bin files, and I have noticed that a substantial proportion of the points (approximately 40% for each frame) have their coordinates set to (0,0,0). This appears to be an unusually high percentage and I am concerned that it might indicate an issue with my processing pipeline. Is this the expected behaviour or am I missing something?

Here's my code for reading the .bin files in Python:

```python
def load_binary(file_path):
    data = np.fromfile(file_path, dtype=np.float32)
    data = data.reshape((-1, 4))  # Assuming the format is x, y, z, intensity
    points = data[:, :3]
    intensity = data[:, 3]

    return points, intensity
```

**Comment by l1997i** [comment]
This issue might be related to the sparsity of the point cloud. You could try visualizing these point clouds first and check if the same problem exists in other frames as well.

**Comment by gfkri** [comment]
The point clouds I examined (e.g. DurLAR_20210716_S) always had the exact size of 262144 points. This indicates that it comes from all recording positions of the spinning LiDAR (128 beams vertically times a "resolution" of 2048 horizontally => 128 x 2048 = 262144). Thus, the point cloud you load from the binary file, also consist all drop outs (getting no return, e.g. due to range > max_range). I would simply filter all points with range smaller some epsilon.
I hope this helps;)
BR

**Comment by l1997i** [comment]
> The point clouds I analyzed (e.g., DurLAR_20210716_S) consistently contained exactly 262,144 points. This suggests that the data includes all recording positions from the spinning LiDAR, which has 128 vertical beams and a horizontal resolution of 2048 points (128 x 2048 = 262,144). Consequently, the loaded point cloud from the binary file includes all dropouts (e.g., no returns due to range exceeding the maximum range). To clean the data, I recommend filtering out all points with a range smaller than a specified epsilon value. I hope this helps;) BR

Thank you very much for your insights. Filtering out those points as a preprocessing step before training is always a good practice and can help improve the quality of the data.

**Comment by samuelss1996** [comment]
> The point clouds I analyzed (e.g., DurLAR_20210716_S) consistently contained exactly 262,144 points. This suggests that the data includes all recording positions from the spinning LiDAR, which has 128 vertical beams and a horizontal resolution of 2048 points (128 x 2048 = 262,144). Consequently, the loaded point cloud from the binary file includes all dropouts (e.g., no returns due to range exceeding the maximum range). To clean the data, I recommend filtering out all points with a range smaller than a specified epsilon value. I hope this helps;) BR

Make so much sense. Thank you
