### ISSUE TITLE
more stable way to download

### ISSUE THREAD

**Issue by zcliangyue** [l1997i/DurLAR#11]
Hi,
I'd like to know if there is a more stable way to download the data, I'm experiencing disconnection issues on all links which makes it completely impossible for me to download the data. By the way, I only need the point cloud data.

**Comment by l1997i** [comment]
We have recently uploaded the DurLAR dataset to OneDrive, which provides fast download speeds from various countries. If you need access to the DurLAR dataset via the OneDrive download link, please send your affiliation/organization, name, and intended usage details to i@luisli.org. We will then provide you with the OneDrive download link.

Feel free to reach out if you have any questions.
