### ISSUE TITLE
数据缺失和时间戳错误

### ISSUE THREAD

**Issue by Zhaohuanfeng** [l1997i/DurLAR#2]
你好！我发现 seq 20210716 缺少 imu.csv文件，另外imu和gps时间戳相对于lidar时间戳滞后了八个小时

**Comment by l1997i** [comment]
Thanks for the issue. We have now confirmed an output bug related to our timestamp. Still fixing this, and will let you know when we solve this immediately. BTW, our latest update drive subsets `20211208` and `20211209` are well time-synchronised and not affected by this.

**Comment by l1997i** [comment]
> 你好！我发现 seq 20210716 缺少 imu.csv文件，另外imu和gps时间戳相对于lidar时间戳滞后了八个小时

Also, I found that the timestamp offset between `lidar/cam1/cam2` and gps was exactly **1 hour**. As a temporal solution before we fix this, I suggest you can simply **add 1 hour offset** to the `lidar/cam1/cam2` topics.
