### ISSUE TITLE
LiDAR-to-camera calibration

### ISSUE THREAD

**Issue by richardmarcus** [l1997i/DurLAR#4]
Hi, thanks for providing this dataset.

I have a question about the calibration files you provide (cam_to_cam, imu_to_lidar and lidar_to_cam).
Is this the result of the calibration process you describe in the paper, including the RANSAC based optimisation for lidar to camera calibration?

And followup questions:
Are the camera images already rectified?

Can, like in  KITTI, a point X in lidar coordinate be projected to the rgb_camera as 

Y = P_rect_02 * R_rect_?? * (R|T)_lidar_to_cam * X

Is this correct? Which is the reference camera coordinate system?

**Comment by l1997i** [comment]
Hi @richardmarcus, thank you for your interest in our dataset and for your questions!

### Calibration Files

Yes, the calibration files we provide (cam_to_cam, imu_to_lidar, and lidar_to_cam) are the result of the calibration process described in our paper, including the RANSAC-based optimization for lidar-to-camera calibration.

### Camera Images Rectification

Yes, the camera images are already rectified. You can directly use the provided projection matrices for your applications.

### Point Projection

You are correct that a point X in the lidar coordinate can be projected to the RGB camera using that equation. The reference camera coordinate system is typically the main front camera (similar to KITTI’s camera 02).

**Comment by richardmarcus** [comment]
Hi, thanks for getting back to me. When using the given calibration data like this, I never managed to get a good alignment between camera and LiDAR. Maybe I still did something wrong, but it seemed to me that one of the calibration files is not the correct one or something like that. 

For my research, I had success with https://github.com/koide3/direct_visual_lidar_calibration for recalibration.
[calib.json](https://github.com/l1997i/DurLAR/files/15483064/calib.json)
Possibly, this is helpful for others who run into the same problem.

**Comment by l1997i** [comment]
Hi @richardmarcus, thank you for getting back to me and sharing your experience. 

The [`calib.json`](https://github.com/l1997i/DurLAR/files/15483064/calib.json) file you provided appears to be on the KITTI dataset. Have you tested the [direct_visual_lidar_calibration](https://github.com/koide3/direct_visual_lidar_calibration) solution on our DurLAR dataset? [direct_visual_lidar_calibration](https://github.com/koide3/direct_visual_lidar_calibration) was not yet published when the DurLAR dataset was released. If you have not tested it on DurLAR, I will attempt to use it to further verify our calibration results and let you know.

**Comment by richardmarcus** [comment]
The calib.json was run on DurLAR, I simply had not changed the naming as I had used a KITTI reference to figure out how to get the ROS format right
![kitti_2011_00_00_drive_0000_synced db3_superglue](https://github.com/l1997i/DurLAR/assets/32901953/817759af-e0d5-4f69-89b7-2adce4667739)

**Comment by l1997i** [comment]
> The calib.json was generated by me with direct_visual_lidar_calibration on DurLAR, I simply had not changed the naming as I had used a KITTI reference to figure out how to get the ROS format right ![kitti_2011_00_00_drive_0000_synced db3_superglue](https://private-user-images.githubusercontent.com/32901953/334844313-817759af-e0d5-4f69-89b7-2adce4667739.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTU2OTUsIm5iZiI6MTcxNjk5NTM5NSwicGF0aCI6Ii8zMjkwMTk1My8zMzQ4NDQzMTMtODE3NzU5YWYtZTBkNS00ZjY5LTg5YjctMmFkY2U0NjY3NzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDE1MDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNjRiMzEyMjRhZDUxMWUwN2Y1M2FjNjcwZDgxZTMyMjlkNjk3OGNlODlhZjhlOGViODQ3YmY4OGM0ZjYyY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ptyQpuhEV2mUhfBx9UXRms9a04kI3rlwBfZS3RilWk)
> 
> ![depth_overlay0000000022](https://private-user-images.githubusercontent.com/32901953/334846166-4784fff8-c9cc-40a6-9c4a-dac106d92206.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5OTU2OTUsIm5iZiI6MTcxNjk5NTM5NSwicGF0aCI6Ii8zMjkwMTk1My8zMzQ4NDYxNjYtNDc4NGZmZjgtYzljYy00MGE2LTljNGEtZGFjMTA2ZDkyMjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDE1MDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiY2UzNDFlMDkxODMzODE5MmFlNzZjMDVhZjQxNmM1NDU3Mzg5Y2Q2OGFlZjZlYWFmODdmMDg3ZWIzYTQ1ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QFmfRL-DEsEeK1RD1JQfTsyhkSXnopfF8Xv3XBNPEgE)

The calibration result looks good based on the visualization. I will further verify the calibration result and update our calibration file as needed. Thank you very much for your feedback and help.

**Comment by ilay-chen** [comment]
Hi,
There is a rosbag file that can be downloaded? Or how can I transfer the data to rosbag? I had many difficulties with https://github.com/tomas789/kitti2bag because the format is different... Maybe you have some code to translate it to kitti format? (the gps+imu, timestamps etc)

Thank you

**Comment by richardmarcus** [comment]
Hi,
I also used kitti2bag, but for direct_visual_lidar_calibration I only needed a few lidar scans and camera images, so I kept the kitti folder structure and copied the data. (If you want to only get the calibration for DurLAR and have no further calibration applications, I would recommend to try my calib.json file because there are a few obstacles to get results)

**Comment by ilay-chen** [comment]
There is no need of the imu and GPS for direct_visual_lidar_calibration? This is my main kitti2bag issue now...
I need to do the calibration my self for my research...
Can you elaborate about your obstacles and how you success?
Thank you!

Maybe there is close to translate the imu and GPS to oxts kitti syle?

**Comment by richardmarcus** [comment]
I don't think you need imu and GPS, the algorithm creates a LiDAR reference from multiple scans via CT-ICP and takes just one camera image. Some things I remember:

- do not use the first few camera frames if the exposure has not yet settled (e.g. for DurLAR)
- consider using another ICP algorithm so that you have more control for the number of frames used, potentially even with support for motion correction/deskewing, and then just provide your merged point_cloud as lidar frame
- you may need the intrinsics and distortion (in case of DurLAR fill it with zeros because camera images are undistorted already)

**Comment by l1997i** [comment]
We conducted a targetless calibration using the [aforementioned method](https://github.com/koide3/direct_visual_lidar_calibration). We have updated the [arxiv version of our paper](https://arxiv.org/pdf/2406.10068) (appendix). 

Additionally, we have included new calibration results and the ROS bag used for the calibration (refer to https://github.com/l1997i/DurLAR?tab=readme-ov-file#get-started). We have also updated the README file to explain and clarify our changes. Hope this will help.

**Comment by Petros626** [comment]
@richardmarcus can you say something about the types of coordinate systems and the yaws?

**Comment by richardmarcus** [comment]
> [@richardmarcus](https://github.com/richardmarcus) can you say something about the types of coordinate systems and the yaws?

Can you provide more information about what you want to know? The coordinate system transformations should be the same as in the KITTI dataset, maybe the KITTI readme answers some of your questions?

[readme.txt](https://github.com/user-attachments/files/20558498/readme.txt)

The author of the paper has also already added the targetless calibration to the readme and the appendix in the paper for more info on that.

Edit: ah, I just saw your other issue, I am afraid I won't be of much further help then, I was just using the matrices and they gave the correct transformations, I never looked into the coordinate system definitions

**Comment by Petros626** [comment]
@richardmarcus Thanks for the quick answer.

Exactly I want to know, if the coordinate system of `KITTI` and `DurLAR` are the same. In their paper the rotation direction of the sensors contradicted my assumptions.

`KITTI`:
Cam: x=right, y=down, z=forward, 
Cam rot_y: CCW around y-axis
LiDAR: x=forward, y=left, z=up
LiDAR rot_z: CW around z-axis

`DurLAR`:
Cam: x=right, y=down, z=forward, 
Cam rot_y: **CW** around y-axis
LiDAR: x=forward, y=left, z=up
LiDAR rot_z: **CCW** around z-axis

Example of the coordinate frames (from paper):
![Image](https://github.com/user-attachments/assets/1b2d94fe-730c-455a-a9ba-50c916fc6e72)

Why these two opposite rotations for the coordinate systems related to `KITTI`? I thought `DurLAR` is also a right-handed coordinate system and follows the rotation logic in `KITTI`

**Comment by Petros626** [comment]
@richardmarcus I saw your edited comment, so I guess my assumptions are correct.
