### ISSUE TITLE
Ouster json calibration file

### ISSUE THREAD

**Issue by patripfr** [l1997i/DurLAR#5]
Hi,
thanks a lot for open sourcing this great dataset!
Could you also share the internal calibration file (json format) of the ouster lidar? An example of this file can be found [here](https://drive.google.com/file/d/1bRdAg8gpXaOYBOMrO6cxpPYbBux4H982/view?usp=sharing).

**Comment by l1997i** [comment]
Here I attach the meta json file of our **Ouster OS1-128** LiDAR. 

Note that, we have erased sensitive information, _e.g.,_ the serial number and unique ID of the device (indicated by _XXXXXXX_). Hope it helps. Cheers!

[os1-128.json.zip](https://github.com/l1997i/DurLAR/files/11960039/os1-128.zip)

**Comment by patripfr** [comment]
Thanks for providing the file so quickly! 
Could you specify in which frame the points in the kitti files are? Is it the same as the "os_sensor" frame from the ouster driver or did you perform any transformation on them?

**Comment by l1997i** [comment]
> Could you specify in which frame the points in the kitti (.bin) files are?

As far as I know, KITTI does not officially provide ROS bag files, so there's no way for me to get the exact frame name. But, it is certain that KITTI point clouds are all collected from the perspective of Velodyne LiDAR.


> did you perform any transformation on them?

No.

> Are the datasets also available in rosbag format somewhere?

We have original rosbag files. If you want, I can send you the Onedrive links. There're also some tools (e.g., [kitti2bag](https://github.com/tomas789/kitti2bag)) that converts KITTI files into huge rosbag files.
