### ISSUE TITLE
How ambient images are generated？

### ISSUE THREAD

**Issue by yscani** [l1997i/DurLAR#6]
Hi, thanks for sharing this dataset.

I would like to know how the ambient images in the data set are generated, and which sensor data is used to generate them.

Thanks.

**Comment by l1997i** [comment]
Hi @yscani,

`ambient` and `reflectivity` panoramic imagery are all come from OS1-128 **LiDAR**. The dimension of the panoramic imagery is $j \times k \times 1$, where $j$ represents the number of beams emitted (for DurLAR, KITTI and nuScenes, $j=128, 64$ and $32$ respectively) and $k$ represents the number of times measurement in one scan cycle [1]. You can refer to [1] for more details getting panoramic imagery (_range image_) from 3D point cloud.

[1] Fan, Lue, Xuan Xiong, Feng Wang, Naiyan Wang, and Zhaoxiang Zhang. "Rangedet: In defense of range view for lidar-based 3d object detection." In Proceedings of the International Conference on Computer Vision (CVPR), IEEE. 2021.

Cheers,
Luis

**Comment by yscani** [comment]
I get it, Thank you very much @l1997i .
