### ISSUE TITLE
Some Data is missing in one sequence of the full dataset

### ISSUE THREAD

**Issue by binyang97** [l1997i/DurLAR#7]
Thank you for providing the awesome dataset!
 
I have downloaded the full dataset which contains five sequence of data. However, I found some data  is missing in the sequence ```DurLAR_20210901```. The folder with name of ```ouster_points``` containing lidar scan is missing in this sequence. Probably it's the issue happening when downloading the full dataset. 

If the data should not be missing, could you provide me a link for downloading the sequence only? It would take too much time to download the full dataset again.

**Comment by l1997i** [comment]
I'm sorry to hear that you've encountered difficulties while downloading our data. 

Considering your situation, the recommended solution we suggest is to visit [Durham University Data Collections](https://collections.durham.ac.uk/collections/r2gq67jr192) of our DurLAR dataset. You can download the data you need based on your situations. You can also verify the integrity of your downloaded files using the MD5 checksums provided.

We hope this resolves your issue. If you have any further questions or concerns, please do not hesitate to let us know.
