### ISSUE TITLE
pcap files

### ISSUE THREAD

**Issue by ilay-chen** [l1997i/DurLAR#8]
Hi,
Thank you for the dataset!
There is a way to get the original pcap files and the calic JSON?

Or - how you translate original .pcap to the .bin?

I need the original .pcap files output for my research...

Thank you!!

**Comment by l1997i** [comment]
Hi @ilay-chen, 

Thank you for reaching out and for your interest in our dataset!

Our original data is in ROS bag format, and we currently do not plan to provide PCAP files. We output the original ROS bag files into BIN format to maintain consistency with widely-used datasets such as KITTI and nuScenes.

**Comment by ilay-chen** [comment]
Thank you for your quick answer!
There is a way to get the original ROS bag?
thank you.

**Comment by l1997i** [comment]
> Thank you for your quick answer! There is a way to get the original ROS bag? thank you.

We do not officially provide ROS bag files. However, you can use other third-party tools for this (refer to https://github.com/l1997i/DurLAR/issues/3#issuecomment-1460372122).

**Comment by ilay-chen** [comment]
Thank you!
